# Generated by Django 5.2 on 2025-04-07 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('railway_reservation_system', '0002_alter_booking_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_date',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='id_proof',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='seat',
        ),
    ]
