# Generated by Django 5.2 on 2025-04-07 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway_reservation_system', '0003_remove_booking_booking_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='pnr',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
