# Generated by Django 5.2 on 2025-04-08 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('railway_reservation_system', '0004_alter_booking_pnr'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fare',
        ),
    ]
