# Generated by Django 5.2 on 2025-04-08 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway_reservation_system', '0005_delete_fare'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='fare',
            field=models.FloatField(default=1300.0),
            preserve_default=False,
        ),
    ]
